-- ====================================================
-- Advanced Seller Analysis
-- ====================================================

-- Seller Revenue Ranking (ranking of sellers based on total revenue)
SELECT *, RANK() OVER(ORDER BY revenue DESC) AS seller_ranking
FROM(SELECT seller_id, ROUND(SUM(price + freight_value), 2) AS revenue
    FROM order_items
    GROUP BY seller_id);

-- Seller Revenue by State (which seller locations generate the most revenue)
SELECT a.seller_state, ROUND(SUM(b.price + b.freight_value), 2) AS revenue
FROM sellers AS a JOIN order_items AS b
ON a.seller_id = b.seller_id
GROUP BY a.seller_state
ORDER BY revenue DESC; 

-- Seller Performance: Orders vs Revenue (compare seller order volume with the revenue they generate)
SELECT seller_id, COUNT(DISTINCT order_id) AS total_orders, ROUND(SUM(price + freight_value), 2) AS revenue
FROM order_items 
GROUP BY seller_id
ORDER BY revenue DESC;

-- Seller Average Rating (sellers receiving the highest customer ratings, avoid sellers with only few reviews)
SELECT a.seller_id, ROUND(AVG(b.review_score), 2) AS avg_rating, COUNT(*) AS review_count
FROM order_items AS a JOIN order_reviews AS b
ON a.order_id = b.order_id
GROUP BY a.seller_id
HAVING COUNT(*) >= 10
ORDER BY avg_rating DESC;

-- Seller Revenue vs Rating (compare commercial performance with customer satisfaction)
SELECT a.seller_id, ROUND(SUM(a.price + a.freight_value), 2) AS revenue, ROUND(AVG(b.review_score), 2) AS avg_rating
FROM order_items AS a JOIN order_reviews AS b
ON a.order_id = b.order_id
GROUP BY a.seller_id
ORDER BY revenue DESC;

-- Seller Revenue Concentration (what percentage of total revenue is generated by the top 10% of sellers)
/* Inner -> Sellerwise revenue, Middle -> Calculate % revenue contribution of each seller & divide entire rows into 10 groups, 
Outer -> Filter top 10% i.e. ntile = 1 & calc sum of revenue contribution which gives % share of top 10 % sellers by revenue  */
SELECT ROUND(SUM(percent_cont), 2) AS top_10_percent_revenue_share
FROM(SELECT *, (revenue/(SUM(revenue) OVER()))*100 AS percent_cont, NTILE(10) OVER(ORDER BY revenue DESC) AS bucket
    FROM(SELECT seller_id, ROUND(SUM(price + freight_value), 2) AS revenue
        FROM order_items
        GROUP BY seller_id))
WHERE bucket = 1;

-- Seller Monthly Performance (how seller revenue changes over time)
SELECT a.seller_id, DATE_TRUNC('month', b.order_purchase_timestamp) AS months, 
    ROUND(SUM(a.price + a.freight_value), 2) AS revenue
FROM order_items AS a JOIN orders AS b
ON a.order_id = b.order_id
GROUP BY a.seller_id, months
ORDER BY a.seller_id, months;
