-- ====================================================
-- Sales Analysis
-- ====================================================

-- Monthly revenue trend = Highest revenue generated in May followed by August and July whereas lowest in September
SELECT EXTRACT(MONTH FROM a.order_purchase_timestamp) as months, ROUND(SUM(b.price + b.freight_value), 2) AS revenue
FROM orders AS a JOIN order_items AS b
ON a.order_id = b.order_id
GROUP BY months
ORDER BY revenue DESC;

-- Monthly Orders = Highest orders placed in August followed by May and July whereas lowest in September
SELECT EXTRACT(MONTH FROM order_purchase_timestamp) as months, COUNT(*) AS order_count
FROM orders
GROUP BY months
ORDER BY order_count DESC;

-- Monthly Average Order Value = Hignest AOV is in Sept folowed by Oct and April whereas lowest is in Feb
SELECT EXTRACT(MONTH FROM a.order_purchase_timestamp) as months, 
        ROUND(SUM(b.price + b.freight_value)/(COUNT(DISTINCT a.order_id)), 2) AS avg_order_value
FROM orders AS a JOIN order_items AS b
ON a.order_id = b.order_id
GROUP BY months
ORDER BY avg_order_value DESC;

-- Revenue by Customer State = Highest revenure generated by state SP, RJ and MG whereas lowest by RR 
SELECT a.customer_state AS state, ROUND(SUM(c.price + c.freight_value), 2) AS revenue 
FROM customers AS a JOIN orders AS b ON a.customer_id = b.customer_id
    JOIN order_items AS c ON b.order_id = c.order_id
GROUP BY state
ORDER BY revenue DESC;

-- Revenue by Product Category = Highest revenue generated by health_beauty whereas lowest by Security_and_services
SELECT product_category_name_english AS category, ROUND(SUM(b.price + b.freight_value), 2) AS revenue
FROM products_trans AS a JOIN order_items AS b
ON a.product_id = b.product_id
GROUP BY category
ORDER BY revenue DESC;

-- Top 10 Products by Revenue
SELECT product_id, ROUND(SUM(price + freight_value), 2) AS revenue
FROM order_items
GROUP BY product_id
ORDER BY revenue DESC
LIMIT 10;

-- Top 10 Sellers by Revenue
SELECT seller_id, ROUND(SUM(price + freight_value), 2) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC
LIMIT 10;
