-- ====================================================
-- Seller Analysis
-- ====================================================

-- Top 10 Sellers by Revenue = Max revenue generated by a single seller is 249640.70
SELECT seller_id, ROUND(SUM(price + freight_value), 2) AS revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC
LIMIT 10;

-- Top 10 Sellers by Orders = Max orders placed by a single seller is 1854 followed by 1806 and 1706
SELECT seller_id, COUNT(DISTINCT order_id) AS total_orders
FROM order_items
GROUP BY seller_id
ORDER BY total_orders DESC
LIMIT 10;

-- Average Order Value per Seller
SELECT seller_id, ROUND(SUM(price + freight_value)/COUNT(DISTINCT order_id), 2) AS avg_order_value
FROM order_items
GROUP BY seller_id
ORDER BY avg_order_value DESC;

-- Seller Revenue by State = Highest revenue is generated in SP state followed by PR and MG
SELECT a.seller_state AS state, ROUND(SUM(b.price + b.freight_value)) As revenue
FROM sellers AS a JOIN order_items AS b
ON a.seller_id = b.seller_id
GROUP BY state
ORDER BY revenue DESC;

-- Top Sellers by Average Product Rating (average product rating of sellers with at least 10 reviews)
SELECT a.seller_id, ROUND(AVG(b.review_score), 2) AS avg_rating, COUNT(*) AS reviews
FROM order_items AS a JOIN order_reviews AS b
ON a.order_id = b.order_id
GROUP BY a.seller_id
HAVING COUNT(*) > 10
ORDER BY avg_rating DESC;

-- Seller Performance — Revenue vs Orders (revenue, no. of orders and average revenue generated for each seller)
SELECT seller_id, ROUND(SUM(price + freight_value), 2) AS revenue, COUNT(DISTINCT order_id) AS orders,
    ROUND(SUM(price + freight_value)/COUNT(DISTINCT order_id), 2) AS avg_revenue
FROM order_items
GROUP BY seller_id
ORDER BY revenue DESC;